= `AceTariffType`
:toclevels: 4


+++The Area Control Error tariff type that is applied or used.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:AceTariffType`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`AceTariffType`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
AceTariffType {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



MarketDocument {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



Unit {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



Point {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




AceTariffType -> MarketDocument: MarketDocument


AceTariffType -> Unit: Unit


AceTariffType -> Point: Point


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<type,`type`>>
| 0..1
| https://w3id.org/linkml/String[`string`]
| +++The coded type of an ACE tariff.+++

| <<MarketDocument,`MarketDocument`>>
| 0..*
| xref::class/MarketDocument.adoc[`MarketDocument`]
| n/a

| <<Point,`Point`>>
| 0..*
| xref::class/Point.adoc[`Point`]
| n/a

| <<Unit,`Unit`>>
| 0..*
| xref::class/Unit.adoc[`Unit`]
| n/a
|===

'''


//[discrete]
[#MarketDocument]
=== `MarketDocument`


[cols="h,4",width=65%]
|===
| URI
| `cim:AceTariffType.MarketDocument`
| Cardinality
| 0..*
| Type
| xref::class/MarketDocument.adoc[`MarketDocument`]


|===

//[discrete]
[#Point]
=== `Point`


[cols="h,4",width=65%]
|===
| URI
| `cim:AceTariffType.Point`
| Cardinality
| 0..*
| Type
| xref::class/Point.adoc[`Point`]


|===

//[discrete]
[#type]
=== `type`
+++The coded type of an ACE tariff.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:AceTariffType.type`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/String[`string`]


|===

//[discrete]
[#Unit]
=== `Unit`


[cols="h,4",width=65%]
|===
| URI
| `cim:AceTariffType.Unit`
| Cardinality
| 0..*
| Type
| xref::class/Unit.adoc[`Unit`]


|===


