= `CombinedCycleTransitionState`
:toclevels: 4


+++Defines the available from and to Transition States for the Combine Cycle Configurations.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:CombinedCycleTransitionState`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`CombinedCycleTransitionState`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
CombinedCycleTransitionState {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



CombinedCycleConfiguration {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



CombinedCycleConfiguration {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




CombinedCycleTransitionState -> CombinedCycleConfiguration: FromConfiguration


CombinedCycleTransitionState -> CombinedCycleConfiguration: ToConfiguration


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<FromConfiguration,`FromConfiguration`>>
| 1
| xref::class/CombinedCycleConfiguration.adoc[`CombinedCycleConfiguration`]
| n/a

| <<ToConfiguration,`ToConfiguration`>>
| 1
| xref::class/CombinedCycleConfiguration.adoc[`CombinedCycleConfiguration`]
| n/a

| <<upTransition,`upTransition`>>
| 0..1
| https://w3id.org/linkml/Boolean[`boolean`]
| +++Flag indicating whether this is an UP transition.
If not, it is a DOWN transition.+++
|===

'''


//[discrete]
[#FromConfiguration]
=== `FromConfiguration`


[cols="h,4",width=65%]
|===
| URI
| `cim:CombinedCycleTransitionState.FromConfiguration`
| Cardinality
| 1
| Type
| xref::class/CombinedCycleConfiguration.adoc[`CombinedCycleConfiguration`]


|===

//[discrete]
[#ToConfiguration]
=== `ToConfiguration`


[cols="h,4",width=65%]
|===
| URI
| `cim:CombinedCycleTransitionState.ToConfiguration`
| Cardinality
| 1
| Type
| xref::class/CombinedCycleConfiguration.adoc[`CombinedCycleConfiguration`]


|===

//[discrete]
[#upTransition]
=== `upTransition`
+++Flag indicating whether this is an UP transition.
If not, it is a DOWN transition.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:CombinedCycleTransitionState.upTransition`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/Boolean[`boolean`]


|===


