= `ControlAreaDesignation`
:toclevels: 4


+++Indicates Control Area associated with self-schedule.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:ControlAreaDesignation`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`ControlAreaDesignation`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
ControlAreaDesignation {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



SubControlArea {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



RegisteredResource {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




ControlAreaDesignation -> SubControlArea: SubControlArea


ControlAreaDesignation -> RegisteredResource: RegisteredResource


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<attained,`attained`>>
| 0..1
| xref::enumeration/YesNo.adoc[`YesNo`]
| +++Attained.+++

| <<native,`native`>>
| 0..1
| xref::enumeration/YesNo.adoc[`YesNo`]
| +++Native.+++

| <<RegisteredResource,`RegisteredResource`>>
| 0..*
| xref::class/RegisteredResource.adoc[`RegisteredResource`]
| n/a

| <<SubControlArea,`SubControlArea`>>
| 0..*
| xref::class/SubControlArea.adoc[`SubControlArea`]
| n/a
|===

'''


//[discrete]
[#attained]
=== `attained`
+++Attained.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:ControlAreaDesignation.attained`
| Cardinality
| 0..1
| Type
| xref::enumeration/YesNo.adoc[`YesNo`]


|===

//[discrete]
[#native]
=== `native`
+++Native.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:ControlAreaDesignation.native`
| Cardinality
| 0..1
| Type
| xref::enumeration/YesNo.adoc[`YesNo`]


|===

//[discrete]
[#RegisteredResource]
=== `RegisteredResource`


[cols="h,4",width=65%]
|===
| URI
| `cim:ControlAreaDesignation.RegisteredResource`
| Cardinality
| 0..*
| Type
| xref::class/RegisteredResource.adoc[`RegisteredResource`]


|===

//[discrete]
[#SubControlArea]
=== `SubControlArea`


[cols="h,4",width=65%]
|===
| URI
| `cim:ControlAreaDesignation.SubControlArea`
| Cardinality
| 0..*
| Type
| xref::class/SubControlArea.adoc[`SubControlArea`]


|===


