= `DiagramObjectGluePoint`
:toclevels: 4


+++This is used for grouping diagram object points from different diagram objects that are considered to be glued together in a diagram even if they are not at the exact same coordinates.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:DiagramObjectGluePoint`


| CIM standard (perspective)
| IEC61970 (Grid)



|===

== Class hierarchy
* *`DiagramObjectGluePoint`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
DiagramObjectGluePoint {
  style {
    fill: "#eccfcb"
    shadow: true
  }
}



DiagramObjectPoint {
  style {
    fill: "#eccfcb"
    shadow: true
  }
}




DiagramObjectGluePoint -> DiagramObjectPoint: DiagramObjectPoints


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<DiagramObjectPoints,`DiagramObjectPoints`>>
| 1..*
| xref::class/DiagramObjectPoint.adoc[`DiagramObjectPoint`]
| +++A diagram object glue point is associated with 2 or more object points that are considered to be 'glued' together.+++
|===

'''


//[discrete]
[#DiagramObjectPoints]
=== `DiagramObjectPoints`
+++A diagram object glue point is associated with 2 or more object points that are considered to be 'glued' together.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:DiagramObjectGluePoint.DiagramObjectPoints`
| Cardinality
| 1..*
| Type
| xref::class/DiagramObjectPoint.adoc[`DiagramObjectPoint`]


|===


