= `EndDeviceEventDetail`
:toclevels: 4


+++Name-value pair, specific to end device events.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:EndDeviceEventDetail`


| CIM standard (perspective)
| IEC61968 (Enterprise)



|===

== Class hierarchy
* *`EndDeviceEventDetail`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
EndDeviceEventDetail {
  style {
    fill: "#d1e7c2"
    shadow: true
  }
}



StringQuantity {
  style {
    fill: "#eccfcb"
    shadow: true
  }
}



EndDeviceEvent {
  style {
    fill: "#d1e7c2"
    shadow: true
  }
}




EndDeviceEventDetail -> StringQuantity: value


EndDeviceEventDetail -> EndDeviceEvent: EndDeviceEvent


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<EndDeviceEvent,`EndDeviceEvent`>>
| 0..1
| xref::class/EndDeviceEvent.adoc[`EndDeviceEvent`]
| +++End device owning this detail.+++

| <<name,`name`>>
| 0..1
| https://w3id.org/linkml/String[`string`]
| +++Name.+++

| <<value,`value`>>
| 0..1
| xref::class/StringQuantity.adoc[`StringQuantity`]
| +++Value, including unit information.+++
|===

'''


//[discrete]
[#EndDeviceEvent]
=== `EndDeviceEvent`
+++End device owning this detail.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:EndDeviceEventDetail.EndDeviceEvent`
| Cardinality
| 0..1
| Type
| xref::class/EndDeviceEvent.adoc[`EndDeviceEvent`]


|===

//[discrete]
[#name]
=== `name`
+++Name.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:EndDeviceEventDetail.name`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/String[`string`]


|===

//[discrete]
[#value]
=== `value`
+++Value, including unit information.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:EndDeviceEventDetail.value`
| Cardinality
| 0..1
| Type
| xref::class/StringQuantity.adoc[`StringQuantity`]


|===


