= `ExpectedEnergyValues`
:toclevels: 4


+++Model Expected Energy from Market Clearing.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:ExpectedEnergyValues`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`ExpectedEnergyValues`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
ExpectedEnergyValues {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



ExpectedEnergy {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



RegisteredResource {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




ExpectedEnergyValues -> ExpectedEnergy: ExpectedEnergy


ExpectedEnergyValues -> RegisteredResource: RegisteredResource


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<ExpectedEnergy,`ExpectedEnergy`>>
| 1
| xref::class/ExpectedEnergy.adoc[`ExpectedEnergy`]
| n/a

| <<RegisteredResource,`RegisteredResource`>>
| 0..1
| xref::class/RegisteredResource.adoc[`RegisteredResource`]
| n/a

| <<energyTypeCode,`energyTypeCode`>>
| 0..1
| https://w3id.org/linkml/String[`string`]
| n/a

| <<expectedMwh,`expectedMwh`>>
| 0..1
| https://w3id.org/linkml/Float[`float`]
| n/a
|===

'''


//[discrete]
[#energyTypeCode]
=== `energyTypeCode`


[cols="h,4",width=65%]
|===
| URI
| `cim:ExpectedEnergyValues.energyTypeCode`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/String[`string`]


|===

//[discrete]
[#ExpectedEnergy]
=== `ExpectedEnergy`


[cols="h,4",width=65%]
|===
| URI
| `cim:ExpectedEnergyValues.ExpectedEnergy`
| Cardinality
| 1
| Type
| xref::class/ExpectedEnergy.adoc[`ExpectedEnergy`]


|===

//[discrete]
[#expectedMwh]
=== `expectedMwh`


[cols="h,4",width=65%]
|===
| URI
| `cim:ExpectedEnergyValues.expectedMwh`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/Float[`float`]


|===

//[discrete]
[#RegisteredResource]
=== `RegisteredResource`


[cols="h,4",width=65%]
|===
| URI
| `cim:ExpectedEnergyValues.RegisteredResource`
| Cardinality
| 0..1
| Type
| xref::class/RegisteredResource.adoc[`RegisteredResource`]


|===


