= `ExPostLossResults`
:toclevels: 4


+++Model results of ex-post calculation of MW losses. Summarizes loss in two categories losses on the the extra high voltage transmission and total losses. Calculated for each subcontrol area.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:ExPostLossResults`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`ExPostLossResults`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
ExPostLossResults {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



ExPostLoss {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



SubControlArea {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




ExPostLossResults -> ExPostLoss: ExPostLoss


ExPostLossResults -> SubControlArea: SubControlArea


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<ExPostLoss,`ExPostLoss`>>
| 1
| xref::class/ExPostLoss.adoc[`ExPostLoss`]
| n/a

| <<SubControlArea,`SubControlArea`>>
| 0..1
| xref::class/SubControlArea.adoc[`SubControlArea`]
| n/a

| <<ehvLossMW,`ehvLossMW`>>
| 0..1
| https://w3id.org/linkml/Float[`float`]
| +++EHV MW losses in the company 
Attribute Usage: Information purposes - Output of LPA engine.+++

| <<totalLossMW,`totalLossMW`>>
| 0..1
| https://w3id.org/linkml/Float[`float`]
| +++Total MW losses in the company 
Attribute Usage: Information purposes - Output of LPA engine.+++
|===

'''


//[discrete]
[#ehvLossMW]
=== `ehvLossMW`
+++EHV MW losses in the company 
Attribute Usage: Information purposes - Output of LPA engine.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:ExPostLossResults.ehvLossMW`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/Float[`float`]


|===

//[discrete]
[#ExPostLoss]
=== `ExPostLoss`


[cols="h,4",width=65%]
|===
| URI
| `cim:ExPostLossResults.ExPostLoss`
| Cardinality
| 1
| Type
| xref::class/ExPostLoss.adoc[`ExPostLoss`]


|===

//[discrete]
[#SubControlArea]
=== `SubControlArea`


[cols="h,4",width=65%]
|===
| URI
| `cim:ExPostLossResults.SubControlArea`
| Cardinality
| 0..1
| Type
| xref::class/SubControlArea.adoc[`SubControlArea`]


|===

//[discrete]
[#totalLossMW]
=== `totalLossMW`
+++Total MW losses in the company 
Attribute Usage: Information purposes - Output of LPA engine.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:ExPostLossResults.totalLossMW`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/Float[`float`]


|===


