= `ExPostPricingResults`
:toclevels: 4


+++Model of ex-post pricing of nodes.  Includes LMP information, pnode based.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:ExPostPricingResults`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`ExPostPricingResults`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
ExPostPricingResults {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



ExPostPricing {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



Pnode {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




ExPostPricingResults -> ExPostPricing: ExPostPricing


ExPostPricingResults -> Pnode: Pnode


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<ExPostPricing,`ExPostPricing`>>
| 1
| xref::class/ExPostPricing.adoc[`ExPostPricing`]
| n/a

| <<Pnode,`Pnode`>>
| 1
| xref::class/Pnode.adoc[`Pnode`]
| n/a

| <<congestLMP,`congestLMP`>>
| 0..1
| https://w3id.org/linkml/Float[`float`]
| +++Congestion component of Location Marginal Price (LMP) in monetary units per MW; congestion component of the hourly LMP at a specific pricing node 
Attribute Usage: Result of the Security, Pricing, and Dispatch(SPD)/Simultaneous Feasibility Test(SFT) software and denotes the hourly congestion component of LMP for each pricing node.+++

| <<lmp,`lmp`>>
| 0..1
| https://w3id.org/linkml/Float[`float`]
| +++5 min weighted average LMP; the Location Marginal Price of the Pnode for which price calculation is carried out. 
Attribute Usage: 5 min weighted average LMP  to be displayed on UI+++

| <<lossLMP,`lossLMP`>>
| 0..1
| https://w3id.org/linkml/Float[`float`]
| +++Loss component of Location Marginal Price (LMP) in monetary units per MW; loss component of the hourly LMP at a specific pricing node 
Attribute Usage: Result of the Security, Pricing, and Dispatch(SPD)/Simultaneous Feasibility Test(SFT) software and denotes the hourly loss component of LMP for each pricing node.+++
|===

'''


//[discrete]
[#congestLMP]
=== `congestLMP`
+++Congestion component of Location Marginal Price (LMP) in monetary units per MW; congestion component of the hourly LMP at a specific pricing node 
Attribute Usage: Result of the Security, Pricing, and Dispatch(SPD)/Simultaneous Feasibility Test(SFT) software and denotes the hourly congestion component of LMP for each pricing node.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:ExPostPricingResults.congestLMP`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/Float[`float`]


|===

//[discrete]
[#ExPostPricing]
=== `ExPostPricing`


[cols="h,4",width=65%]
|===
| URI
| `cim:ExPostPricingResults.ExPostPricing`
| Cardinality
| 1
| Type
| xref::class/ExPostPricing.adoc[`ExPostPricing`]


|===

//[discrete]
[#lmp]
=== `lmp`
+++5 min weighted average LMP; the Location Marginal Price of the Pnode for which price calculation is carried out. 
Attribute Usage: 5 min weighted average LMP  to be displayed on UI+++

[cols="h,4",width=65%]
|===
| URI
| `cim:ExPostPricingResults.lmp`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/Float[`float`]


|===

//[discrete]
[#lossLMP]
=== `lossLMP`
+++Loss component of Location Marginal Price (LMP) in monetary units per MW; loss component of the hourly LMP at a specific pricing node 
Attribute Usage: Result of the Security, Pricing, and Dispatch(SPD)/Simultaneous Feasibility Test(SFT) software and denotes the hourly loss component of LMP for each pricing node.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:ExPostPricingResults.lossLMP`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/Float[`float`]


|===

//[discrete]
[#Pnode]
=== `Pnode`


[cols="h,4",width=65%]
|===
| URI
| `cim:ExPostPricingResults.Pnode`
| Cardinality
| 1
| Type
| xref::class/Pnode.adoc[`Pnode`]


|===


