= `MarketLedger`
:toclevels: 4


+++In accounting transactions, a ledger is a book containing accounts to which debits and credits are posted from journals, where transactions are initially recorded. Journal entries are periodically posted to the ledger. Ledger actual represents actual amounts by account within ledger within company or within business area. Actual amounts may be generated in a source application and then loaded to a specific ledger within the enterprise general ledger or budget application.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:MarketLedger`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`MarketLedger`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
MarketLedger {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



MarketLedgerEntry {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




MarketLedger -> MarketLedgerEntry: MarketLedgerEntries


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<MarketLedgerEntries,`MarketLedgerEntries`>>
| 0..*
| xref::class/MarketLedgerEntry.adoc[`MarketLedgerEntry`]
| n/a
|===

'''


//[discrete]
[#MarketLedgerEntries]
=== `MarketLedgerEntries`


[cols="h,4",width=65%]
|===
| URI
| `cim:MarketLedger.MarketLedgerEntries`
| Cardinality
| 0..*
| Type
| xref::class/MarketLedgerEntry.adoc[`MarketLedgerEntry`]


|===


