= `Name`
:toclevels: 4


+++The Name class provides the means to define any number of human readable  names for an object. A name is <b>not</b> to be used for defining inter-object relationships. For inter-object relationships instead use the object identification 'mRID'.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:Name`


| CIM standard (perspective)
| IEC61970 (Grid)



|===

== Class hierarchy
* *`Name`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
Name {
  style {
    fill: "#eccfcb"
    shadow: true
  }
}



NameType {
  style {
    fill: "#eccfcb"
    shadow: true
  }
}



IdentifiedObject {
  style {
    fill: "#eccfcb"
    shadow: true
  }
}




Name -> NameType: NameType


Name -> IdentifiedObject: IdentifiedObject


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<IdentifiedObject,`IdentifiedObject`>>
| 1
| xref::class/IdentifiedObject.adoc[`IdentifiedObject`]
| +++Identified object that this name designates.+++

| <<NameType,`NameType`>>
| 1
| xref::class/NameType.adoc[`NameType`]
| +++Type of this name.+++

| <<name,`name`>>
| 0..1
| https://w3id.org/linkml/String[`string`]
| +++Any free text that name the object.+++
|===

'''


//[discrete]
[#IdentifiedObject]
=== `IdentifiedObject`
+++Identified object that this name designates.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:Name.IdentifiedObject`
| Cardinality
| 1
| Type
| xref::class/IdentifiedObject.adoc[`IdentifiedObject`]


|===

//[discrete]
[#name]
=== `name`
+++Any free text that name the object.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:Name.name`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/String[`string`]


|===

//[discrete]
[#NameType]
=== `NameType`
+++Type of this name.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:Name.NameType`
| Cardinality
| 1
| Type
| xref::class/NameType.adoc[`NameType`]


|===


