= `ResourceVerifiableCosts`
:toclevels: 4


+++This class is defined to describe the verifiable costs associated with a generation resource.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:ResourceVerifiableCosts`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`ResourceVerifiableCosts`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
ResourceVerifiableCosts {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



MktHeatRateCurve {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



RegisteredResource {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



ResourceStartupCost {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



ResourceOperationMaintenanceCost {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




ResourceVerifiableCosts -> MktHeatRateCurve: MktHeatRateCurve


ResourceVerifiableCosts -> RegisteredResource: RegisteredResource


ResourceVerifiableCosts -> ResourceStartupCost: ResourceStartupCost


ResourceVerifiableCosts -> ResourceOperationMaintenanceCost: ResourceOperationMaintenanceCost


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<MktHeatRateCurve,`MktHeatRateCurve`>>
| 1
| xref::class/MktHeatRateCurve.adoc[`MktHeatRateCurve`]
| n/a

| <<RegisteredResource,`RegisteredResource`>>
| 1
| xref::class/RegisteredResource.adoc[`RegisteredResource`]
| n/a

| <<ResourceOperationMaintenanceCost,`ResourceOperationMaintenanceCost`>>
| 1
| xref::class/ResourceOperationMaintenanceCost.adoc[`ResourceOperationMaintenanceCost`]
| n/a

| <<ResourceStartupCost,`ResourceStartupCost`>>
| 0..*
| xref::class/ResourceStartupCost.adoc[`ResourceStartupCost`]
| n/a
|===

'''


//[discrete]
[#MktHeatRateCurve]
=== `MktHeatRateCurve`


[cols="h,4",width=65%]
|===
| URI
| `cim:ResourceVerifiableCosts.MktHeatRateCurve`
| Cardinality
| 1
| Type
| xref::class/MktHeatRateCurve.adoc[`MktHeatRateCurve`]


|===

//[discrete]
[#RegisteredResource]
=== `RegisteredResource`


[cols="h,4",width=65%]
|===
| URI
| `cim:ResourceVerifiableCosts.RegisteredResource`
| Cardinality
| 1
| Type
| xref::class/RegisteredResource.adoc[`RegisteredResource`]


|===

//[discrete]
[#ResourceOperationMaintenanceCost]
=== `ResourceOperationMaintenanceCost`


[cols="h,4",width=65%]
|===
| URI
| `cim:ResourceVerifiableCosts.ResourceOperationMaintenanceCost`
| Cardinality
| 1
| Type
| xref::class/ResourceOperationMaintenanceCost.adoc[`ResourceOperationMaintenanceCost`]


|===

//[discrete]
[#ResourceStartupCost]
=== `ResourceStartupCost`


[cols="h,4",width=65%]
|===
| URI
| `cim:ResourceVerifiableCosts.ResourceStartupCost`
| Cardinality
| 0..*
| Type
| xref::class/ResourceStartupCost.adoc[`ResourceStartupCost`]


|===


