= `SwitchStatus`
:toclevels: 4


+++Optimal Power Flow or State Estimator Circuit Breaker Status.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:SwitchStatus`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`SwitchStatus`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
SwitchStatus {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



MktSwitch {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




SwitchStatus -> MktSwitch: MktSwitch


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<MktSwitch,`MktSwitch`>>
| 1
| xref::class/MktSwitch.adoc[`MktSwitch`]
| n/a

| <<switchStatus,`switchStatus`>>
| 0..1
| xref::enumeration/SwitchStatusType.adoc[`SwitchStatusType`]
| +++Circuit Breaker Status (closed or open) of the circuit breaker from the power flow.+++
|===

'''


//[discrete]
[#MktSwitch]
=== `MktSwitch`


[cols="h,4",width=65%]
|===
| URI
| `cim:SwitchStatus.MktSwitch`
| Cardinality
| 1
| Type
| xref::class/MktSwitch.adoc[`MktSwitch`]


|===

//[discrete]
[#switchStatus]
=== `switchStatus`
+++Circuit Breaker Status (closed or open) of the circuit breaker from the power flow.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:SwitchStatus.switchStatus`
| Cardinality
| 0..1
| Type
| xref::enumeration/SwitchStatusType.adoc[`SwitchStatusType`]


|===


