= `TradingHubValues`
:toclevels: 4


+++Models prices at Trading Hubs.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:TradingHubValues`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`TradingHubValues`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
TradingHubValues {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



AggregatedPnode {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



TradingHubPrice {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




TradingHubValues -> AggregatedPnode: AggregatedPnode


TradingHubValues -> TradingHubPrice: TradingHubPrice


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<AggregatedPnode,`AggregatedPnode`>>
| 1
| xref::class/AggregatedPnode.adoc[`AggregatedPnode`]
| n/a

| <<TradingHubPrice,`TradingHubPrice`>>
| 1
| xref::class/TradingHubPrice.adoc[`TradingHubPrice`]
| n/a

| <<price,`price`>>
| 0..1
| https://w3id.org/linkml/Float[`float`]
| +++Utilizes the Market type. For DA, the price is hourly. For RTM the price is a 5 minute price.+++
|===

'''


//[discrete]
[#AggregatedPnode]
=== `AggregatedPnode`


[cols="h,4",width=65%]
|===
| URI
| `cim:TradingHubValues.AggregatedPnode`
| Cardinality
| 1
| Type
| xref::class/AggregatedPnode.adoc[`AggregatedPnode`]


|===

//[discrete]
[#price]
=== `price`
+++Utilizes the Market type. For DA, the price is hourly. For RTM the price is a 5 minute price.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:TradingHubValues.price`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/Float[`float`]


|===

//[discrete]
[#TradingHubPrice]
=== `TradingHubPrice`


[cols="h,4",width=65%]
|===
| URI
| `cim:TradingHubValues.TradingHubPrice`
| Cardinality
| 1
| Type
| xref::class/TradingHubPrice.adoc[`TradingHubPrice`]


|===


