= `TradeProduct`
:toclevels: 4


+++<b>TradeType</b>                                        <b>TradeProduct</b>
IST  (InterSC Trade)                          PHY (Physical Energy Trade)
IST                                                  APN (Energy Trades at Aggregated Pricing Nodes)
IST                                                  CPT (Converted Physical Energy Trade)
AST (Ancilliary Services Trade)             RUT (Regulation Up Trade)
AST                                                 RDT (Regulation Down Trade)
AST                                                 SRT (Spinning Reserve Trade)
AST                                                 NRT (Non-Spinning Reserve Trade)
UCT (Unit Commitment Trade)            null+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:TradeProduct`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`TradeProduct`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
TradeProduct {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



Trade {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




TradeProduct -> Trade: Trade


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<tradeProductType,`tradeProductType`>>
| 0..1
| https://w3id.org/linkml/String[`string`]
| +++PHY (Physical Energy Trade);  
APN (Energy Trades at Aggregated Pricing Nodes);  
CPT (Converted Physical Energy Trade);  
RUT (Regulation Up Trade);  
RDT (Regulation Down Trade);  
SRT (Spinning Reserve Trade);  
NRT (Non-Spinning Reserve Trade)+++

| <<tradeType,`tradeType`>>
| 0..1
| xref::enumeration/TradeType.adoc[`TradeType`]
| +++IST  - InterSC Trade;  
AST - Ancilliary Services Trade;  
UCT - Unit Commitment Trade+++

| <<Trade,`Trade`>>
| 0..*
| xref::class/Trade.adoc[`Trade`]
| n/a
|===

'''


//[discrete]
[#Trade]
=== `Trade`


[cols="h,4",width=65%]
|===
| URI
| `cim:TradeProduct.Trade`
| Cardinality
| 0..*
| Type
| xref::class/Trade.adoc[`Trade`]


|===

//[discrete]
[#tradeProductType]
=== `tradeProductType`
+++PHY (Physical Energy Trade);  
APN (Energy Trades at Aggregated Pricing Nodes);  
CPT (Converted Physical Energy Trade);  
RUT (Regulation Up Trade);  
RDT (Regulation Down Trade);  
SRT (Spinning Reserve Trade);  
NRT (Non-Spinning Reserve Trade)+++

[cols="h,4",width=65%]
|===
| URI
| `cim:TradeProduct.tradeProductType`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/String[`string`]


|===

//[discrete]
[#tradeType]
=== `tradeType`
+++IST  - InterSC Trade;  
AST - Ancilliary Services Trade;  
UCT - Unit Commitment Trade+++

[cols="h,4",width=65%]
|===
| URI
| `cim:TradeProduct.tradeType`
| Cardinality
| 0..1
| Type
| xref::enumeration/TradeType.adoc[`TradeType`]


|===


