= `TREntitlement`
:toclevels: 4


+++A Transmission Right(TR) can be a chain of TR's or on individual. 

When a transmission right is not a chain, this is formally the ETC/TOR Entitlement for each ETC/TOR contract with the inclusion of CVR(Converted Rights) as an ETC. This is the sum of all entitlements on all related transmission interfaces for the same TR.

When TR is a chain, its entitlement is the minimum of all entitlements for the individual TRs in the chain.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:TREntitlement`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`TREntitlement`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
TREntitlement {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



ContractRight {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




TREntitlement -> ContractRight: TransmissionContractRight


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<TransmissionContractRight,`TransmissionContractRight`>>
| 1
| xref::class/ContractRight.adoc[`ContractRight`]
| n/a

| <<entitlement,`entitlement`>>
| 0..1
| https://w3id.org/linkml/Float[`float`]
| +++The entitlement+++

| <<startOperatingDate,`startOperatingDate`>>
| 0..1
| https://w3id.org/linkml/Date[`date`]
| +++Operating date and hour when the entitlement applies+++
|===

'''


//[discrete]
[#entitlement]
=== `entitlement`
+++The entitlement+++

[cols="h,4",width=65%]
|===
| URI
| `cim:TREntitlement.entitlement`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/Float[`float`]


|===

//[discrete]
[#startOperatingDate]
=== `startOperatingDate`
+++Operating date and hour when the entitlement applies+++

[cols="h,4",width=65%]
|===
| URI
| `cim:TREntitlement.startOperatingDate`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/Date[`date`]


|===

//[discrete]
[#TransmissionContractRight]
=== `TransmissionContractRight`


[cols="h,4",width=65%]
|===
| URI
| `cim:TREntitlement.TransmissionContractRight`
| Cardinality
| 1
| Type
| xref::class/ContractRight.adoc[`ContractRight`]


|===


