site:
  title: TC57CIM
  url: http://localhost:8080
  start_page: ROOT::index.adoc
content:
  sources:
    - url: ''
      branches: [cim*]
      start_path: src/docs
asciidoc:
  attributes:
    page-pagination: ''
    experimental: ''
    kroki-fetch-diagram: false  # Whether rendering is done server-sided so the images are served statically.
    kroki-default-format: svg@
    kroki-server-url: http://fruit.ritger.nl:9000
  extensions:
    - asciidoctor-kroki
output:
  clean: true
  dir: output/docs/html
ui:
  bundle:
    url: https://github.com/Netbeheer-Nederland/antora-nbnl-ui/releases/download/1.0/ui-bundle.zip
antora:
  extensions:
    - require: '@antora/collector-extension'
    - require: '@antora/lunr-extension'
