= `FlowgateRelief`
:toclevels: 4


+++IDC (Interchange Distribution Calulator) sends data for a TLR (Transmission Loading Relief).+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:FlowgateRelief`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`FlowgateRelief`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
FlowgateRelief {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



Flowgate {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




FlowgateRelief -> Flowgate: Flowgate


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<Flowgate,`Flowgate`>>
| 1
| xref::class/Flowgate.adoc[`Flowgate`]
| n/a

| <<effectiveDate,`effectiveDate`>>
| 0..1
| https://w3id.org/linkml/Date[`date`]
| +++Date/Time when record becomes effective 
Used to determine when a record becomes effective.+++

| <<idcTargetMktFlow,`idcTargetMktFlow`>>
| 0..1
| https://w3id.org/linkml/Integer[`integer`]
| +++Energy Flow level that should be maintained according to the TLR rules as specified by the IDC. 
For Realtime Markets use in dispatch to control constraints under TLR and calculate unconstrained market flows+++

| <<terminateDate,`terminateDate`>>
| 0..1
| https://w3id.org/linkml/Date[`date`]
| +++Date/Time when record is no longer effective 
Used to determine when a record is no longer effective+++
|===

'''


//[discrete]
[#effectiveDate]
=== `effectiveDate`
+++Date/Time when record becomes effective 
Used to determine when a record becomes effective.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:FlowgateRelief.effectiveDate`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/Date[`date`]


|===

//[discrete]
[#Flowgate]
=== `Flowgate`


[cols="h,4",width=65%]
|===
| URI
| `cim:FlowgateRelief.Flowgate`
| Cardinality
| 1
| Type
| xref::class/Flowgate.adoc[`Flowgate`]


|===

//[discrete]
[#idcTargetMktFlow]
=== `idcTargetMktFlow`
+++Energy Flow level that should be maintained according to the TLR rules as specified by the IDC. 
For Realtime Markets use in dispatch to control constraints under TLR and calculate unconstrained market flows+++

[cols="h,4",width=65%]
|===
| URI
| `cim:FlowgateRelief.idcTargetMktFlow`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/Integer[`integer`]


|===

//[discrete]
[#terminateDate]
=== `terminateDate`
+++Date/Time when record is no longer effective 
Used to determine when a record is no longer effective+++

[cols="h,4",width=65%]
|===
| URI
| `cim:FlowgateRelief.terminateDate`
| Cardinality
| 0..1
| Type
| https://w3id.org/linkml/Date[`date`]


|===


