= `InadvertentAccount`
:toclevels: 4


+++An account for tracking inadvertent interchange versus time for each control area. A control area may have more than one inadvertent account in order to track inadvertent over one or more specific tie points in addition to the usual overall net inadvertent. Separate accounts would also be used to track designated time periods, such as on-peak and off-peak.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI
| `cim:InadvertentAccount`


| CIM standard (perspective)
| IEC62325 (Market)



|===

== Class hierarchy
* *`InadvertentAccount`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
InadvertentAccount {
  style {
    fill: "#fffbef"
    shadow: true
  }
}



SubControlArea {
  style {
    fill: "#fffbef"
    shadow: true
  }
}




InadvertentAccount -> SubControlArea: SubControlArea


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinality | Type | Description

| <<SubControlArea,`SubControlArea`>>
| 1
| xref::class/SubControlArea.adoc[`SubControlArea`]
| +++A control area can have one or more net inadvertent interchange accounts+++
|===

'''


//[discrete]
[#SubControlArea]
=== `SubControlArea`
+++A control area can have one or more net inadvertent interchange accounts+++

[cols="h,4",width=65%]
|===
| URI
| `cim:InadvertentAccount.SubControlArea`
| Cardinality
| 1
| Type
| xref::class/SubControlArea.adoc[`SubControlArea`]


|===


