name: Build and publish site
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
concurrency:
  group: github-pages
  cancel-in-progress: false
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Setup Python 3.12.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.7"
      - name: Install Python project dependencies
        run: pip install -r requirements.txt
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Antora
        run: npm i
      - name: Generate site
        run: just build
      - name: DEBUG
        run: find
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/docs/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
